name: CI/CD

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: backup/do
          file: backup/do/Dockerfile
          push: true
          tags: salvatoreemilio/curt:latest,salvatoreemilio/curt:0.0.1
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: SSH setup
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd dev/curt/;
            git pull;
            docker compose pull;
            docker compose down;
            docker compose up -d;
            docker image prune -a -f;
          "
      - name: Cleanup
        run: rm -rf ~/.ssh/id_rsa
